version: 2

jobs:

   build:
     working_directory: ~/workspace
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - restore_cache:
           key: dependency-cache-{{ checksum "build.gradle" }}
       - run:
           command: ./gradlew resolveDependencies
       - save_cache:
           key: dependency-cache-{{ checksum "build.gradle" }}
           paths:
             - ~/.gradle/caches
             - ~/.gradle/wrapper
       - run:
           command: ./gradlew clean build
       - run:
           command: mkdir ~/test-results
       - run:
           command: find ~/workspace -type f -regex ".*/test-results/.*xml" -exec ln {} ~/test-results/ \;
       - store_test_results:
           path: ~/test-results
       - store_artifacts:
           path: ~/test-results
       - store_artifacts:
           path: build/libs

   publish:
     working_directory: ~/workspace
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - restore_cache:
           key: dependency-cache-{{ checksum "build.gradle" }}
       - run:
           command: ./gradlew assemble testJar
       - run:
           command: ./.circleci/publishOnCommitMsg.sh

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master